apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops
spec:
  selector:
    matchLabels:
      app: gitops
  template:
    metadata:
      labels:
        app: gitops
    spec:
      containers:
      - name: gitops
        image: gitops
        ports:
        - containerPort: 3000
