name: CI CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            web-dashgo:v${{ github.run_number }}
            web-dashgo:latest

      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18.x
      #     cache: 'npm'

      # - name: Install dependencies
      #   run: npm install

      # - name: Linting
      #   run: npm run lint

      # - name: Testing
      #   run: npm run test

      # - name: Build
      #   run: npm run build
